### ISSUE TITLE
chown error on new machine

### ISSUE THREAD

**Issue by jakecraige** [dieterdemeyer/puppet-eclipse#1]
``` sh
Debug: Prefetching compressed_app resources for package
Debug: Executing '/usr/bin/curl http://eclipse.mirror.triple-it.nl/technology/epp/downloads/release/kepler/SR1/eclipse-java-kepler-SR1-macosx-cocoa-x86_64.tar.gz -Lqo /opt/boxen/cache/Eclipse-Java-Kepler-SR1.app.tar.gz'
Debug: Executing '/bin/rm -rf /Applications/Eclipse-Java-Kepler-SR1.app'
Debug: Executing '/usr/bin/tar -zxf /opt/boxen/cache/Eclipse-Java-Kepler-SR1.app.tar.gz -C /Applications'
Debug: Executing '/usr/sbin/chown -R Ronak:staff /Applications/Eclipse-Java-Kepler-SR1.app'
Error: Execution of '/usr/sbin/chown -R Ronak:staff /Applications/Eclipse-Java-Kepler-SR1.app' returned 1: chown: /Applications/Eclipse-Java-Kepler-SR1.app: No such file or directory
Error: /Stage[main]/Eclipse::Java/Package[Eclipse-Java-Kepler-SR1]/ensure: change from absent to present failed: Execution of '/usr/sbin/chown -R Ronak:staff /Applications/Eclipse-Java-Kepler-SR1.app' returned 1: chown: /Applications/Eclipse-Java-Kepler-SR1.app: No such file or directory
```

Looks like eclipse us in `/Applications/eclipse/Eclipse.app` and the app path and resource name not matching [puppet-boxen source](https://github.com/boxen/puppet-boxen/blob/master/lib/puppet/provider/package/compressed_app.rb#L63)

I'm not sure how to fix this or I'd submit a PR for it. If anyone knows how to let me know. 

What's weird is that it's in the same path on my machine but doesn't give an error

Thanks

**Comment by dieterdemeyer** [comment]
@jakecraige I'll see if I can reproduce the error and I'll get back to you..

**Comment by dieterdemeyer** [comment]
@jakecraige I've tried it myself and it's indeed failing on the package name.
On the upside, Eclipse is getting installed and you can use it but you're getting that failed message...
But I think the compressed_app type and provider need to be modified for this to work without errors.

**Comment by leeyoda** [comment]
I am getting similar errors and it takes really long for the failed message to process. (2 minutes+)
And you are right, Eclipse does get installed.

**Comment by leeyoda** [comment]
https://github.com/boxen/puppet-eclipse/issues/10
Don't how to link ticket, but I ran into the similar errors.
